sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 2423137093
  alioss:
    endpoint: oss-cn-hongkong.aliyuncs.com
    access-key-id: LTAI5tE88jFMf3Pwc1jBK9PM
    access-key-secret: XnAk9sFzVpgqGNf9ZIqwRNxGfR83kO
    bucket-name: sky-take-out-tyb
  redis:
    host: localhost
    port: 6379
    #password:
    database: 0
